config/routes.rb
require 'sidekiq/pro/web'

Rails.application.routes.draw do

  root 'plans#index'
  get 'sales', to: 'sales#index', as: 'sales'
  get 'home', to: 'home#index', as: 'home'
  get :dashboard, to: 'dashboard#index'
  
  get 'terms', to: 'home#terms', as: 'terms'
  get 'earnings_disclaimer', to: 'home#earnings_disclaimer', as: 'earnings_disclaimer'
  get 'general_disclaimer', to: 'home#general_disclaimer', as: 'general_disclaimer'

  get 'domains/:id' => "sites#index", as: :domains
  
  get 'copy_to_clipboard' => 'application#copy_to_clipboard', as: :copy_to_clipboard
  
  resource :subscriptions
  get 'create_trial_for_existing_customer' => 'subscriptions#create_trial_for_existing_customer', as: :create_trial_for_existing_customer
  get 'reactivate' => 'subscriptions#reactivate', as: :reactivate
  
  resources :pages
  resources :plans

  resources :users
  resources :sessions
  resources :password_resets
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get :account, to: 'users#account'

  resources :sites do
    collection do
      put 'sites/:id/save_bookmarked' => "sites#save_bookmarked", as: :save_bookmarked
      put 'sites/:id/unbookmark' => "sites#unbookmark", as: :unbookmark
      get ':id/bookmarked' => "sites#bookmarked", as: :bookmarked
    end
  end
  get 'sites/:id/urls' => "sites#all_urls", as: :all_urls
  get 'sites/:id/internal' => "sites#internal", as: :internal
  get 'sites/:id/external' => "sites#external", as: :external
  get 'sites/:id/broken' => "sites#broken", as: :broken
  get 'sites/:id/available' => "sites#available", as: :available

  resources :crawls
  get 'projects/' => "crawls#index", as: :projects
  get 'running_crawls' => "crawls#running", as: :running_crawls
  get 'finished_crawls' => "crawls#finished", as: :finished_crawls
  get 'projects/new' => "crawls#new", as: :new_project
  get 'projects/:id' => "crawls#show", as: :crawl_path
  get 'stop_crawl/:id' => 'crawls#stop_crawl', as: :stop_crawl
  post 'shut_down_crawl' => 'crawls#shut_down_crawl', as: :shut_down_crawl
  get 'crawls/keyword/new' => 'crawls#new_keyword_crawl', as: :new_keyword_crawl
  post 'crawls/keyword/create' => 'crawls#create_keyword_crawl', as: :create_keyword_crawl
  get 'crawls/reverse/new' => 'crawls#new_reverse_crawl', as: :new_reverse_crawl
  post 'crawls/reverse/create' => 'crawls#create_reverse_crawl', as: :create_reverse_crawl
  post 'api_create', to: 'crawls#api_create'
  post 'fetch_new_crawl', to: 'crawls#fetch_new_crawl'
  post 'call_crawl', to: 'crawls#call_crawl'
  post 'migrate_db', to: 'crawls#migrate_db'
  post 'process_new_crawl', to: 'crawls#process_new_crawl'
  get 'start_crawl', to: 'crawls#start_crawl', as: :start_crawl
  get 'delete_crawl/:id', to: 'crawls#delete_crawl', as: :delete_crawl

  resources :pending_crawls do
    collection {post :sort}
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/controllers/pending_crawls_controller.rb
class PendingCrawlsController < ApplicationController
  before_action :authorize, :except => [:sort]
  
  def index
    @nav = 'projects'
    processor_names = ['processor', 'processor_one', 'processor_two']
    crawls_array = []
    processor_names.each do |processor|
      crawls_array << HerokuApp.using("#{processor}").where(status: 'pending', user_id: current_user.id).order(:position).includes(:crawl).flatten
    end
    page = params[:page].nil? ? 1 : params[:page]
    @crawls = crawls_array.flatten.paginate(:page => page, :per_page => 10)
    # @crawls = HerokuApp.using(:processor).where(status: "pending", user_id: current_user.id).order(:position).includes(:crawl)
  end
  
  def sort
    params[:heroku_app].each_with_index do |id, index|
      HerokuApp.using(:processor).update(id, position: index+1)
    end
    render nothing: true
  end
  
end

app/helpers/pending_crawls_helper.rb
module PendingCrawlsHelper
end

app/views/pending_crawls/index.html.erb
<div class="main_page_container">

	<div class="container-fluid header_title_container">
		<div class="row">
			<div class="col-xs-12">
				<div class="header_title_content">
					<div class='top_nav_title_container'>
						<div class="header_glyph">
							<span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
						</div>
						<div class="header_text">
							<p>Projects</p>
						</div>
					</div>
					<div class="blue-nav">
            <ul class="nav">
              <li>
                <%= link_to 'Projects', crawls_path %>
              </li>

              <li class="active">
                <%= link_to 'Pending', pending_crawls_path %>
                <div class="arrow-down"></div>
              </li>

              <li>
                <%= link_to 'Running', running_crawls_path %>
              </li>

              <li>
                <%= link_to 'Stopped', '#' %>
              </li>

              <li>
                <%= link_to 'Finished', finished_crawls_path %>
              </li>
            </ul>
					</div>
				  <%= link_to 'Help & Support', 'http://source-wave.com/support', class: 'pull-right help-support' %>
          <div class="header_button pull-right">
            <p><%= link_to "Create New", new_project_path, class: 'btn btn-green btn-sm', 'data-no-turbolink': true %></p>
          </div>
				</div>
			</div>
		</div>
	</div>

	<div class="container-fluid container_section pending-crawls-list-container">

		<div class="row">
			<div class='col-xs-12'>
        <%= render 'minutes/used_minutes' %>
        <div class="page-header">
          <h3>Click and drag to sort the order</h3>
        </div>
        <ul class="pending-crawls-container" data-update-url="<%= sort_pending_crawls_url %>">
					<% @crawls.each do |c| %>

						<% if c.crawl %>
							<%= content_tag_for :li, c do %>
                <div class='pending-crawl'>
                  <div class='row'>
                    <div class='handle_div'>
                      <span class="handle glyphicon glyphicon-align-justify" aria-hidden="true"></span>
                    </div>
                    <div class='name crawl-name col-xs-3'>
                      <%= c.crawl.name %>
                    </div>
                    <div class='name col-xs-3'>
                      Pages Per Site: <strong><%= c.crawl.maxpages %></strong>
                    </div>
                    <div class='name col-xs-3'>
                      Type: <strong><%= c.crawl.crawl_type %></strong>
                    </div>
                    <%= link_to "DELETE", crawl_path(c.id, 'processor_name' => c.processor_name), class: 'btn btn-red-hollow btn-sm pull-right', method: :delete, data: { confirm: "Are you sure?" } %>
                    <%= link_to "START", start_crawl_path('processor_name' => c.processor_name), class: 'btn btn-green btn-sm pull-right'%>
                  </div>
                </div>
							<% end %>
						<% end %>

					<% end %>
				</ul>

			</div>
		</div>
	</div>

</div>