config/routes.rb
require 'sidekiq/pro/web'

Rails.application.routes.draw do

  root 'plans#index'
  get 'sales', to: 'sales#index', as: 'sales'
  get 'home', to: 'home#index', as: 'home'
  get :dashboard, to: 'dashboard#index'
  
  get 'terms', to: 'home#terms', as: 'terms'
  get 'earnings_disclaimer', to: 'home#earnings_disclaimer', as: 'earnings_disclaimer'
  get 'general_disclaimer', to: 'home#general_disclaimer', as: 'general_disclaimer'

  get 'domains/:id' => "sites#index", as: :domains
  
  get 'copy_to_clipboard' => 'application#copy_to_clipboard', as: :copy_to_clipboard
  
  resource :subscriptions
  get 'create_trial_for_existing_customer' => 'subscriptions#create_trial_for_existing_customer', as: :create_trial_for_existing_customer
  get 'reactivate' => 'subscriptions#reactivate', as: :reactivate
  
  resources :pages
  resources :plans

  resources :users
  resources :sessions
  resources :password_resets
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get :account, to: 'users#account'

  resources :sites do
    collection do
      put 'sites/:id/save_bookmarked' => "sites#save_bookmarked", as: :save_bookmarked
      put 'sites/:id/unbookmark' => "sites#unbookmark", as: :unbookmark
      get ':id/bookmarked' => "sites#bookmarked", as: :bookmarked
    end
  end
  get 'sites/:id/urls' => "sites#all_urls", as: :all_urls
  get 'sites/:id/internal' => "sites#internal", as: :internal
  get 'sites/:id/external' => "sites#external", as: :external
  get 'sites/:id/broken' => "sites#broken", as: :broken
  get 'sites/:id/available' => "sites#available", as: :available

  resources :crawls
  get 'projects/' => "crawls#index", as: :projects
  get 'running_crawls' => "crawls#running", as: :running_crawls
  get 'finished_crawls' => "crawls#finished", as: :finished_crawls
  get 'projects/new' => "crawls#new", as: :new_project
  get 'projects/:id' => "crawls#show", as: :crawl_path
  get 'stop_crawl/:id' => 'crawls#stop_crawl', as: :stop_crawl
  post 'shut_down_crawl' => 'crawls#shut_down_crawl', as: :shut_down_crawl
  get 'crawls/keyword/new' => 'crawls#new_keyword_crawl', as: :new_keyword_crawl
  post 'crawls/keyword/create' => 'crawls#create_keyword_crawl', as: :create_keyword_crawl
  get 'crawls/reverse/new' => 'crawls#new_reverse_crawl', as: :new_reverse_crawl
  post 'crawls/reverse/create' => 'crawls#create_reverse_crawl', as: :create_reverse_crawl
  post 'api_create', to: 'crawls#api_create'
  post 'fetch_new_crawl', to: 'crawls#fetch_new_crawl'
  post 'call_crawl', to: 'crawls#call_crawl'
  post 'migrate_db', to: 'crawls#migrate_db'
  post 'process_new_crawl', to: 'crawls#process_new_crawl'
  get 'start_crawl', to: 'crawls#start_crawl', as: :start_crawl
  get 'delete_crawl/:id', to: 'crawls#delete_crawl', as: :delete_crawl

  resources :pending_crawls do
    collection {post :sort}
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/controllers/crawls_controller.rb
class CrawlsController < ApplicationController
  before_action :authorize, :except => [:api_create, :migrate_db, :process_new_crawl, :shut_down_crawl]
  skip_before_action :verify_authenticity_token, :only => [:api_create, :migrate_db, :process_new_crawl, :shut_down_crawl]
  
  def index
    processor_names = ['processor', 'processor_one', 'processor_two', 'processor_three', 'processor_four']
    crawls_array = []
    processor_names.each do |processor|
      # crawls_array << Crawl.using("#{processor}").where(user_id: current_user.id).order('created_at').limit(10).flatten
      begin
        crawls_array << Crawl.using("#{processor}").where(user_id: current_user.id)
      rescue
        
      end
    end
    page = params[:page].nil? ? 1 : params[:page] 
    @crawls = crawls_array.flatten.sort_by{|record| record.created_at}.reverse.paginate(:page => page, :per_page => 10)
    
  end
  
  def running
    
    processor_names = ['processor', 'processor_one', 'processor_two', 'processor_three', 'processor_four']
    crawls_array = []
    processor_names.each do |processor|
      # crawls_array << Crawl.using("#{processor}").where(status: 'running', user_id: current_user.id).order('created_at').limit(10).flatten
      crawls_array << Crawl.using("#{processor}").where(status: 'running', user_id: current_user.id)
    end
    page = params[:page].nil? ? 1 : params[:page] 
    @crawls = crawls_array.flatten.sort_by{|record| record.created_at}.reverse.paginate(:page => page, :per_page => 10)
    
    # @crawls = Crawl.using(:processor).where(status: 'running', user_id: current_user.id).order('created_at').page(params[:page]).per_page(10)
  end
  
  def finished
    
    processor_names = ['processor', 'processor_one', 'processor_two', 'processor_three', 'processor_four']
    crawls_array = []
    processor_names.each do |processor|
      # crawls_array << Crawl.using("#{processor}").where(status: 'finished', user_id: current_user.id).order('created_at').limit(10).flatten
      crawls_array << Crawl.using("#{processor}").where(status: 'finished', user_id: current_user.id).order('created_at').flatten
    end
    page = params[:page].nil? ? 1 : params[:page] 
    @crawls = crawls_array.flatten.paginate(:page => page, :per_page => 10)
    
    # @crawls = Crawl.using(:processor).where(status: 'finished', user_id: current_user.id).order('created_at').page(params[:page]).per_page(10)
  end
  
  def show
    processor_name = params['processor_name']
    @project = Crawl.using("#{processor_name}").where(user_id: current_user.id, id: params[:id]).first
    
    
    if @project.status == 'running' && !@project.redis_url.nil?
      begin
        redis = ActiveSupport::Cache.lookup_store(:redis_store, @project.redis_url)
        urls_found = "crawl/#{@project.id}/urls_found"
        expired_domains = "crawl/#{@project.id}/expired_domains"
        broken_domains = "crawl/#{@project.id}/broken_domains"
        progress = "crawl/#{@project.id}/progress"
        stats = redis.read_multi(urls_found, expired_domains, broken_domains, progress, raw: true)
        @urls_found = stats[urls_found].to_i
        @broken_domains = stats[broken_domains].to_i
        @expired_domains = stats[expired_domains].to_i
        @progress = stats[progress].to_f
      rescue
        @urls_found = @project.total_urls_found.to_i
        @broken_domains = @project.total_broken.to_i
        @expired_domains = @project.total_expired.to_i
      end
    else
      @urls_found = @project.total_urls_found.to_i
      @broken_domains = @project.total_broken.to_i
      @expired_domains = @project.total_expired.to_i
    end
    
    @stats_chart = Crawl.crawl_stats(@broken_domains, @expired_domains)
    # @sites = Site.find(@project.process_links_batches.map(&:site_id))
    @sites = @project.sites.page(params[:page]).per_page(10)
    @top_domains = @project.pages.where(available: 'true').limit(5)
  end

  def new
    @project = current_user.crawls.new
  end
  
  def new_keyword_crawl
    @project = current_user.crawls.new
  end
  
  def create
    Crawl.delay.save_new_crawl(current_user.id, params[:urls], params[:crawl])
    redirect_to crawls_path
  end
  
  def new_reverse_crawl
    @project = current_user.crawls.new
  end
  
  def create_reverse_crawl
    Crawl.delay.save_new_reverse_crawl(current_user.id, params[:url], params[:crawl])
    redirect_to crawls_path
  end
  
  def edit
    @project = Crawl.using(params["processor_name"]).find(params[:id])
    total_minutes = @project.total_minutes.to_f
    if total_minutes > 0
      if total_minutes > 60
        split_total_time = (total_minutes.to_f/60.to_f).round(2).to_s.split('.')
        @hours = split_total_time[0]
        @minutes = split_total_time[1]
      else
        @hours = 0
        @minutes = total_minutes
      end
    else
      @hours = 0
      @minutes = 0
    end
  end
  
  def create_keyword_crawl
    Crawl.delay.save_new_keyword_crawl(current_user.id, params[:crawl][:keyword], params[:crawl])
    redirect_to crawls_path
  end
  
  def process_new_crawl
    @json = JSON.parse(request.body.read)
    puts "crawl to process hash #{@json["options"]}"
    Crawl.delay.decision_maker(@json["options"])
    render :layout => false
  end
  
  def api_create
    @json = JSON.parse(request.body.read)
    puts "here is the json hash #{@json["options"]}"
    Crawl.delay.start_crawl(@json["options"])
    SidekiqStats.delay.start(@json["options"])
    render :layout => false
  end
  
  def migrate_db
    @json = JSON.parse(request.body.read)
    processor_name = @json["options"]['processor_name']
    if @json["options"]["iteration"].to_i == 1
      
      crawl = Crawl.using("#{processor_name}").find(@json["options"]["crawl_id"].to_i)
      master_url = ENV['DATABASE_URL']
      slave_keys = ENV.keys.select{|k| k =~ /HEROKU_POSTGRESQL_.*_URL/}
      db_url_name = (slave_keys - ["HEROKU_POSTGRESQL_COPPER_URL", "HEROKU_POSTGRESQL_AMBER_URL","HEROKU_POSTGRESQL_NAVY_URL","HEROKU_POSTGRESQL_WHITE_URL", "HEROKU_POSTGRESQL_BROWN_URL"])
      puts "migrate db: the db url name is #{db_url_name[0]}"
      db_url = ENV[db_url_name[0]]
      
      db_split = db_url.split(':')[1..3]
      
      db_user = db_split[0].split('//')[1]
      db_pass = db_split[1].split('@')[0]
      db_host = db_split[1].split('@')[1]
      db_port = db_split[2].split('/')[0].to_i
      db_name = db_split[2].split('/')[1]
      
      crawl.update(db_url: db_url)
      puts "setting the database variables"
      
      heroku = Heroku::API.new(:api_key => 'f901d1da-4e4c-432f-9c9c-81da8363bb91')
      heroku = Heroku::API.new(:username => 'hello@biznobo.com', :password => '2025Ishmael')
      heroku.put_config_vars("revivecrawler#{@json["options"]["crawl_id"]}", 'DATABASE_URL' => db_url, 'DB_USER' => db_user, 'DB_PASS' => db_pass, 'DB_HOST' => db_host, 'DB_PORT' => db_port, 'DB_NAME' => db_name)
      
      # heroku.set_db_config_vars("revivecrawler#{@json["options"]["crawl_id"]}", db_url)
      
    else
      
      puts "second iteration about to migrate the database"
      heroku = Heroku::API.new(:api_key => 'f901d1da-4e4c-432f-9c9c-81da8363bb91')
      heroku = Heroku::API.new(:username => 'hello@biznobo.com', :password => '2025Ishmael')
      heroku.post_ps("revivecrawler#{@json["options"]["crawl_id"]}", "rake db:migrate")
      sleep 5
      puts "migrate_db: database migrate and restarting app"
      heroku.post_ps("revivecrawler#{@json["options"]["crawl_id"]}", "restart")
      
    end
    render :layout => false
  end
  
  def destroy
    crawl = HerokuApp.using(params["processor_name"]).find(params[:id])
    crawl.destroy
    redirect_to crawls_path
  end
  
  def delete_crawl
    crawl = Crawl.using(params["processor_name"]).find(params[:id])
    crawl.delete
    redirect_to crawls_path
  end
  
  def start_crawl
    Api.delay.process_new_crawl(user_id: current_user.id, 'processor_name' => params['processor_name'])
    redirect_to crawls_path
  end
  
  def stop_crawl
    puts "stop the crawl with the ID #{params[:id]} in the processor #{params['processor_name']}"
    # Crawl.delay.stop_crawl(params[:id], 'processor_name' => params['processor_name'])
    # Crawl.delay.shut_down('crawl_id' => params[:id])
    Api.delay.stop_crawl('crawl_id' => params[:id], 'processor_name' => params['processor_name'])
    redirect_to crawls_path
  end
  
  def shut_down_crawl
    @json = JSON.parse(request.body.read)
    crawl_id = @json["options"]['crawl_id']
    processor_name = @json["options"]['processor_name']
    Crawl.delay.shut_down('crawl_id' => crawl_id, 'processor_name' => processor_name)
    render :layout => false
  end
  
end

app/helpers/crawls_helper.rb
module CrawlsHelper
end

app/views/crawls/_project_row.html.erb
<div class="row">
	
	<% @crawls.each do |s| %>
			
			<div class="col-xs-6 crawls_index_action_stats_container">
	
				<div class="row">
			
					<div class="panel panel-default">
						<div class="panel-heading panel_blue_heading clearfix project_panel_heading">
							<div class="pull-left">
								<p><%= s.name %></p>
							</div>
							<div class="pull-right">
								<p><%= link_to "VIEW", crawl_path_path(s.id, 'processor_name' => s.processor_name) %></p>
							</div>
						</div>
						<div class="panel-body">
					
							<%= render 'project_stats', s: s %>
					
						</div>
					</div>
			
				</div>
	
			</div>
		
	<% end %>

</div>

app/views/crawls/_project_stats.html.erb
<ul class="project_stats_container text-center">
	
	<li class="col-xs-3 fill nopadding">
		<div class="stat_title">
			SITES
		</div>
		<div class="stat_value">
			<%= link_to s.total_sites.to_i, "#" %>
		</div>
	</li>
	
	<li class="col-xs-3 fill nopadding">
		<div class="stat_title">
			URLS
		</div>
		<div class="stat_value">
			<%= link_to s.total_urls_found.to_i, '#' %>
		</div>
	</li>
	
	<li class="col-xs-3 fill nopadding">
		<div class="stat_title">
			BROKEN
		</div>
		<div class="stat_value">
			<%= link_to s.total_broken.to_i, broken_path(s.id, 'processor_name' => s.processor_name) %>
		</div>
	</li>
	
	<li class="col-xs-3 fill nopadding">
		<div class="stat_title">
			AVAILABLE
		</div>
		<div class="stat_value">
			<%= link_to s.total_expired.to_i, available_path(id: s.id, 'processor_name' => s.processor_name) %>
		</div>
	</li>
	
</ul>
	

app/views/crawls/_projects_list_view.html.erb
					<div class="panel panel-default">
						<div class="panel-heading panel_blue_heading panel_glyph_container">
							
							<div class="header_glyph">
								<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
							</div>
							<div class="header_text">
								<p>Crawls</p>
							</div>
							
						</div>
						<div class="panel-body">
							
							<table class="table table-hover table-striped">
								
								<thead>
									<tr>
										<!-- <th></th> -->
										<th class='col-xs-3'>NAME</th>
										<th class="text-center">SITES</th>
										<th class="text-center">URLS</th>
										<th class="text-center">BROKEN</th>
										<th class="text-center">AVAILABLE</th>
										<th class="text-center">STATUS</th>
										<th class="text-center"></th>
									</tr>
								</thead>
								
								<tbody>
									
									<% @crawls.each do |crawl| %>
										
										<tr>
											<!-- <td>
												<span class="glyphicon glyphicon-trash glyph_pink" aria-hidden="true"></span>
												<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
											</td> -->

											<td><%= link_to crawl.name, crawl_path_path(crawl.id, 'processor_name' => crawl.processor_name), class: 'blue_text' %></td>
											<td class="text-center blue_text"><%= crawl.total_sites %></td>
											<td class="text-center blue_text"><%= crawl.total_urls_found %></td>
											<td class="text-center">
												<%= link_to crawl.total_broken.to_i, broken_path(crawl.id, 'processor_name' => crawl.processor_name), class: 'blue_text' %>
											</td>
											<td class="text-center">
												<%= link_to crawl.total_expired.to_i, available_path(id: crawl.id, 'processor_name' => crawl.processor_name), class: 'blue_text' %>
											</td>
											<td class="text-center blue_text"><%= crawl.status %></td>

											<td>
												
												<% if crawl.status == 'running' %>
													
													<%= link_to "Stop", stop_crawl_path(crawl.id, 'processor_name' => crawl.processor_name), data: {confirm: "Are you sure?"}, class: 'btn btn-warning btn-sm' %>
													
												<% else %>
												
													<%= link_to "Delete", delete_crawl_path(crawl.id, 'processor_name' => crawl.processor_name), data: {confirm: "Are you sure?"}, class: 'btn btn-danger btn-sm' %>
												
												<% end %>
												
												<%= link_to "View", crawl_path_path(crawl.id, 'processor_name' => crawl.processor_name), class: 'btn btn-primary btn-sm'%>
												
											</td>
										</tr>
										
									<% end %>
									
								</tbody>

							</table>
							
							<!-- <div class="will_paginate_container text-center">
								<%#= will_paginate @sites, renderer: BootstrapPagination::Rails %>
							</div> -->
							
						</div>
					</div>
					

app/views/crawls/_tabs.html.erb
<div class="tabbable-panel">
	<div class="tabbable-line">
		<ul class="nav nav-tabs ">
			
			<li class="active">
				<%= link_to '#' do %>
				    <i class="glyphicon glyphicon-stats">
						<span class="glyph_text">Dashboard</span>
					</i>
				<% end %>
			</li>
			
			<li >
				<%= link_to domains_path(@project.id) do %>
				    <i class="glyphicon glyphicon-list-alt">
						<span class="glyph_text">Sites</span>
					</i>
				<% end %>
			</li>
			
		</ul>
	</div>
</div>

app/views/crawls/index.html.erb
<div class="main_page_container">

	<div class="container-fluid header_title_container">
		<div class="row">
			<div class="col-xs-12">
				<div class="header_title_content">
					<div class='top_nav_title_container'>
						<div class="header_glyph">
							<span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
						</div>
						<div class="header_text">
							<p>Projects</p>
						</div>
					</div>
					<div class="blue-nav">
            <ul class="nav">
              <li class="active">
                <%= link_to 'Projects', crawls_path %>
                <div class="arrow-down"></div>
              </li>

              <li>
                <%= link_to 'Pending', pending_crawls_path %>
              </li>

              <li >
                <%= link_to 'Running', running_crawls_path %>
              </li>

              <li >
                <%= link_to 'Stopped', '#' %>
              </li>

              <li >
                <%= link_to 'Finished', finished_crawls_path %>
              </li>
            </ul>
					</div>
				  <%= link_to 'Help & Support', 'http://source-wave.com/support', class: 'pull-right help-support' %>
          <div class="header_button pull-right">
            <p><%= link_to "Create New", new_project_path, class: 'btn btn-green btn-sm', 'data-no-turbolink': true %></p>
          </div>
				</div>
			</div>
		</div>
	</div>



	<div class="container-fluid container_section">

		<%= render 'minutes/used_minutes' %>

		<%= render 'project_row' %>

		<div class="will_paginate_container text-center">
			<%= will_paginate @crawls, renderer: BootstrapPagination::Rails %>
		</div>

	</div>

</div>

app/views/crawls/new.html.erb
<div class="main_page_container">

	<div class="container-fluid header_title_container">
		<div class="row">
			<div class="col-xs-12">
				<div class="header_title_content">
					<div class='top_nav_title_container'>
						<div class="header_glyph">
							<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
						</div>
						<div class="header_text">
							<p>Add New</p>
						</div>
					</div>
          <div class="blue-nav">
            <ul class='nav'>
              <li class="active">
                <%= link_to 'URL Crawl', new_crawl_path %>
                <div class="arrow-down"></div>
              </li>
              <li>
                <%= link_to 'Keyword Crawl', new_keyword_crawl_path %>
              </li>
              <li>
                <%= link_to 'Reverse Crawl', new_reverse_crawl_path %>
              </li>
            </ul>
          </div>
				</div>
			</div>
		</div>
	</div>

	<div class="container-fluid container_section">
		<div class="row">
			<div class="col-xs-12">
				<div class="row">
					<div class="panel panel-success panel-round">
						<div class="panel-heading panel_blue_heading panel_glyph_container">
							<div class='header_text'>
								<p>URL Crawl</p>
							</div>
						</div>
						<div class="panel-body">
							<%= render 'form' %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/crawls/new_keyword_crawl.html.erb
<div class="main_page_container">

	<div class="container-fluid header_title_container">
		<div class="row">
			<div class="col-xs-12">
				<div class="header_title_content">
					<div class='top_nav_title_container'>
						<div class="header_glyph">
							<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
						</div>
						<div class="header_text">
							<p>Add New</p>
						</div>
					</div>
					<div class="blue-nav">
            <ul class="nav">
              <li>
                <%= link_to 'URL Crawl', new_crawl_path %>
              </li>
              <li class="active">
                <%= link_to 'Keyword Crawl', new_keyword_crawl_path %>
                <div class="arrow-down"></div>
              </li>
              <li>
                <%= link_to 'Reverse Crawl', new_reverse_crawl_path %>
              </li>
            </ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container-fluid container_section">
		<div class="row">
			<div class="col-xs-12">
				<div class="row">
					<div class="panel panel-default panel-round">
						<div class="panel-heading panel_blue_heading panel_glyph_container">
							<div class='header_text'>
								<p>Keyword Crawl</p>
							</div>
						</div>
						<div class="panel-body">
							<%= render 'keyword_form' %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/crawls/show.html.erb
<div class="main_page_container">
	
	<div class="container-fluid header_title_container">
		<div class="row">
			<div class="col-xs-12">
				<div class="header_title_content">
						
					<!-- TABS -->
					
						<div class="tabbable-panel">
						<div class="tabbable-line">
							<ul class="nav nav-tabs ">
			
								<li class="active">
									<%= link_to crawl_path_path(@project.id, 'processor_name' => @project.processor_name) do %>
									    <i class="glyphicon glyphicon-stats">
											<span class="glyph_text">Dashboard</span>
										</i>
									<% end %>
								</li>
			
								<li >
									<%= link_to broken_path(@project.id, 'processor_name' => @project.processor_name) do %>
									    <i class="glyphicon glyphicon-ban-circle">
											<span class="glyph_text">Broken</span>
										</i>
									<% end %>
								</li>
								
								<li >
									<%= link_to available_path(@project.id, 'processor_name' => @project.processor_name) do %>
									    <i class="glyphicon glyphicon-ok">
											<span class="glyph_text">Available</span>
										</i>
									<% end %>
								</li>
								
								<li>
									<%= link_to bookmarked_sites_path(@project.id, 'processor_name' => @project.processor_name) do %>
									    <i class="glyphicon glyphicon-bookmark">
											<span class="glyph_text">Bookmarked</span>
										</i>
									<% end %>
								</li>
								
								<li>
									<%= link_to edit_crawl_path(@project.id, 'processor_name' => @project.processor_name) do %>
									    <i class="glyphicon glyphicon-bookmark">
											<span class="glyph_text">Settings</span>
										</i>
									<% end %>
								</li>
								
								<% if @project.status != 'finished' %>
									
									<div class="pull-right">
										<%= link_to 'Stop Crawl', stop_crawl_path(@project.id, 'processor_name' => @project.processor_name), data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
									</div>
									
								<% else %>
								
									<div class="pull-right">
										<%= link_to 'Delete Project', delete_crawl_path(@project.id, 'processor_name' => @project.processor_name), data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
									</div>
									
								<% end %>
			
							</ul>
							

							
						</div>
						
					</div>
					
					<!-- TABS -->

						
				</div>
			</div>
		</div>
	</div>
	
	<div class="container-fluid container_section">
		<div class="row">
			<div class="col-xs-12">
				<div class="row">
					
					<% if @progress %>
						<div class="progress">
						  <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="<%= @progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @progress %>%">
						    <span class="sr-only"><%= @progress %> Complete</span>
						  </div>
						</div>
					<% else %>
						
					<% end %>
				
				</div>
			</div>
		</div>
	</div>
	
	
	<div class='container-fluid container_section'>
		<div class='row'>
					
			<div class='col-xs-12 text-center'>
						<div class='panel'>
							<div class='panel-body'>
								<div class='row'>

									<div class='col-xs-3 dashboard_stats_container'>
										<div class='title_text'>
											<p>URLS FOUND</p>
										</div>
										<div class='row'>
											<div class='stat_circle_container glyph_blue'>
												<%= @urls_found.to_i %>
											</div>
										</div>
									</div>
									
									<div class='col-xs-3 dashboard_stats_container'>
										<div class='title_text'>
											<p>BROKEN DOMAINS</p>
										</div>
										<div class='row'>
											<div class='stat_circle_container glyph_blue'>
												<%= @broken_domains.to_i %>
											</div>
										</div>
									</div>
									
									<div class='col-xs-3 dashboard_stats_container'>
										<div class='title_text'>
											<p>EXPIRED DOMAINS</p>
										</div>
										<div class='row'>
											<div class='stat_circle_container glyph_blue'>
												<%= @expired_domains.to_i %>
											</div>
										</div>
									</div>
									
									<div class='col-xs-3 dashboard_stats_container'>
										

										<div class="row">
											<div class="title_text">
												<% if @project.status.to_s == 'running' %>
													<p>TIME RUNNING</p>
												<% else %>
													<p>STATUS</p>
												<% end %>
								
											</div>
										</div>
					
										<div class="row">
											<div class="stat_circle_container glyph_blue">
												<% if @project.status.to_s == 'running' %>
													<%= content_tag "div", class: 'crawl_start_time', data: {start_time: (Time.now-@project.created_at).to_i} do %>
													Loading...
													<% end %>
												<% else %>
													<%= @project.status.to_s %>
												<% end %>
											</div>
										</div>
										

									</div>
									
								</div>
							</div>
						</div>
					</div>

		</div>
	</div>
	
	
	<div class="container-fluid container_section">
	
			<div class="row">
		
				<div class="col-xs-12">
			
					<div class="row">
					
						<div class="panel panel-default">
							<div class="panel-heading panel_blue_heading panel_glyph_container">
							
								<div class="header_glyph">
									<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
								</div>
								<div class="header_text">
									<p>PROJECT STATS</p>
								</div>
							
							</div>
							<div class="panel-body">
							
								<%= high_chart("stats_chart", @stats_chart) %>
							
							</div>
						</div>
					
					</div>
			
				</div>
		
			</div>
	
	</div>	

	
	<%= render 'top_domains' %>

	<%= render 'sites_table' %>
	
</div>