config/routes.rb
require 'sidekiq/pro/web'

Rails.application.routes.draw do

  root 'plans#index'
  get 'sales', to: 'sales#index', as: 'sales'
  get 'home', to: 'home#index', as: 'home'
  get :dashboard, to: 'dashboard#index'
  
  get 'terms', to: 'home#terms', as: 'terms'
  get 'earnings_disclaimer', to: 'home#earnings_disclaimer', as: 'earnings_disclaimer'
  get 'general_disclaimer', to: 'home#general_disclaimer', as: 'general_disclaimer'

  get 'domains/:id' => "sites#index", as: :domains
  
  get 'copy_to_clipboard' => 'application#copy_to_clipboard', as: :copy_to_clipboard
  
  resource :subscriptions
  get 'create_trial_for_existing_customer' => 'subscriptions#create_trial_for_existing_customer', as: :create_trial_for_existing_customer
  get 'reactivate' => 'subscriptions#reactivate', as: :reactivate
  
  resources :pages
  resources :plans

  resources :users
  resources :sessions
  resources :password_resets
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get :account, to: 'users#account'

  resources :sites do
    collection do
      put 'sites/:id/save_bookmarked' => "sites#save_bookmarked", as: :save_bookmarked
      put 'sites/:id/unbookmark' => "sites#unbookmark", as: :unbookmark
      get ':id/bookmarked' => "sites#bookmarked", as: :bookmarked
    end
  end
  get 'sites/:id/urls' => "sites#all_urls", as: :all_urls
  get 'sites/:id/internal' => "sites#internal", as: :internal
  get 'sites/:id/external' => "sites#external", as: :external
  get 'sites/:id/broken' => "sites#broken", as: :broken
  get 'sites/:id/available' => "sites#available", as: :available

  resources :crawls
  get 'projects/' => "crawls#index", as: :projects
  get 'running_crawls' => "crawls#running", as: :running_crawls
  get 'finished_crawls' => "crawls#finished", as: :finished_crawls
  get 'projects/new' => "crawls#new", as: :new_project
  get 'projects/:id' => "crawls#show", as: :crawl_path
  get 'stop_crawl/:id' => 'crawls#stop_crawl', as: :stop_crawl
  post 'shut_down_crawl' => 'crawls#shut_down_crawl', as: :shut_down_crawl
  get 'crawls/keyword/new' => 'crawls#new_keyword_crawl', as: :new_keyword_crawl
  post 'crawls/keyword/create' => 'crawls#create_keyword_crawl', as: :create_keyword_crawl
  get 'crawls/reverse/new' => 'crawls#new_reverse_crawl', as: :new_reverse_crawl
  post 'crawls/reverse/create' => 'crawls#create_reverse_crawl', as: :create_reverse_crawl
  post 'api_create', to: 'crawls#api_create'
  post 'fetch_new_crawl', to: 'crawls#fetch_new_crawl'
  post 'call_crawl', to: 'crawls#call_crawl'
  post 'migrate_db', to: 'crawls#migrate_db'
  post 'process_new_crawl', to: 'crawls#process_new_crawl'
  get 'start_crawl', to: 'crawls#start_crawl', as: :start_crawl
  get 'delete_crawl/:id', to: 'crawls#delete_crawl', as: :delete_crawl

  resources :pending_crawls do
    collection {post :sort}
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id                    :integer          not null, primary key
#  user_id               :integer
#  stripe_customer_token :string
#  status                :string
#  plan_id               :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  plan_name             :string
#  trial_end             :string
#
# Indexes
#
#  index_subscriptions_on_user_id  (user_id) UNIQUE
#

class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan

  attr_accessor :stripe_card_token
  attr_accessor :stripe_plan_id
  attr_accessor :trial_end

  validates_presence_of :stripe_customer_token, :message => 'Stripe Error'
  validates :plan, :presence => true
  validates :user, :uniqueness => true

  def save_with_stripe!(stripe_plan = (stripe_plan_id.present? ? stripe_plan_id : false ) || plan_id)
    # It has dynamic stripe plan variable if it exists either set
    # through controller or already on user or passed on call
    # which allows us to use it as upgrade as well.

    valid_params = (user.email && stripe_plan_id.present? && stripe_card_token.present?)

    if valid_params

      # Create customer and Set Card
      if trial_end.to_i == 0
        customer = Stripe::Customer.create(email: user.email, plan: stripe_plan_id, card: stripe_card_token)
      else
        customer = Stripe::Customer.create(email: user.email, plan: stripe_plan_id, card: stripe_card_token, trial_end: trial_end.to_i.days.from_now.to_time.to_i)
      end
      
      # customer.subscriptions.create(plan: stripe_plan)
      
      # Save Plan, Status and Customer Token
      self.update!(status: 'active', stripe_customer_token: customer.id)

    else

      return false

    end

  end

  def subscribe_with_stripe(options={})

    customer = Stripe::Customer.retrieve(stripe_customer_token)
    
    if options['trial_end'].to_i == 0
      sub = customer.subscriptions.create(plan: stripe_plan_id)
    else
      sub = customer.subscriptions.create(plan: stripe_plan_id, trial_end: options['trial_end'].to_i.days.from_now.to_time.to_i)
    end
    
    if sub[:status] == 'active'
      self.update(status: 'active', plan: Plan.find_by_name(stripe_plan_id))
    end

  end

  def unsubscribe_with_stripe
    customer = Stripe::Customer.retrieve(stripe_customer_token)
    sub_id = customer.subscriptions.data.find{|sub| sub[:plan][:id] == plan_id.to_s}[:id]
    delete = customer.subscriptions.retrieve(sub_id).delete
    if delete[:status] == 'canceled'
      self.update(status: 'canceled')
    end

  end

  def active?
    case status
      when 'active'
        true
      when 'canceled' || 'cancelled'
        false
      else
        false
    end
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authorize
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @subscription = Subscription.new
    if params['plan_id'] == "1"
      @price = '199.00'
    else
      @price = '297.00'
    end
    # For ~> checkout
    # If the user already has a plan just redirect to dash
    # in the future this will redirect to account and billing.
    if !current_user.subscription.nil? && current_user.subscription.active?
      redirect_to '/account#subscription'
    else
      render layout: 'checkout'
    end
  end

  # New Stripe Subscription
  def create
    @subscription = Subscription.new(user: current_user, stripe_card_token: params['stripeToken'])

    # Plan
    plan = Plan.using(:main_shard).find_by_name(subscription_params[:plan_id].to_s)
    @subscription.plan = plan

    # User Info
    user_params = subscription_params[:user]

    # Set stripe stuff.
    @subscription.stripe_plan_id = subscription_params[:plan_id]
    @subscription.stripe_card_token = subscription_params[:stripeToken]
    @subscription.trial_end = subscription_params[:trial_end].to_i

    respond_to do |format|

      if plan.present? && @subscription.save_with_stripe!
        # After Successful billing update stripe user with billing details if they are present
        # @subscription.user.update(user_params) if user_params.present?
        @subscription.user.update(user_params)
        format.html { redirect_to '/dashboard', flash:{success: 'Subscription Successful. Welcome to Revive!' } }
      elsif plan.present? == false
        format.html { redirect_to new_subscriptions_path, flash:{error: 'Invalid Plan ID' } }
      else
        format.html { render action: :new, layout: 'checkout' }
      end

    end

  end

  # Re subscribe Stripe
  def update
    @subscription.stripe_plan_id = subscription_params[:plan_id] ||  @subscription.plan.name

    respond_to do |format|
      if @subscription.user == current_user && @subscription.subscribe_with_stripe
        format.html { redirect_to '/dashboard', flash:{success: 'Subscription Successful. Welcome to Back Revive!' } }
      else
        format.html { redirect_to '/account#subscription'}
      end
    end
  end

  # Unsubscribe From Stripe

  def destroy
    respond_to do |format|
      if @subscription.unsubscribe_with_stripe
        format.html { redirect_to dashboard_path, flash:{success: 'Successfully Canceled Subscription. \n We will miss you ' + "#{current_user.first_name}! :(" }}
      else
        format.html { redirect_to dashboard_path,  flash:{success: 'Subscription Cancel Failed.'} }
      end
    end
  end
  
  def create_trial_for_existing_customer
    if current_user.subscription && current_user.subscription.stripe_customer_token
      begin
        customer = Stripe::Customer.retrieve(current_user.subscription.stripe_customer_token)
        if customer
          customer.subscriptions.create(:plan => params['plan_id'], trial_end: params['trial_end'].to_i.days.from_now.to_time.to_i)
          current_user.subscription.status = 'active'
          current_user.subscription.trial_end = "#{params['trial_end'].to_i.days.from_now.to_time.to_i}"
          current_user.subscription.save
        end
        redirect_to dashboard_path, flash:{success: 'Subscription Successful. Welcome Back to Revive!' }
      rescue
        redirect_to dashboard_path, flash:{error: 'Subscription Unsuccessful' }
      end
    end
    
  end
  
  # def upgrade_to_charter
  #   customer = Stripe::Customer.retrieve({CUSTOMER_ID})
  #   subscription = customer.subscriptions.retrieve({SUBSCRIPTION_ID})
  #   subscription.plan = {PLAN_ID}
  #   subscription.save
  # end

  private

  def set_subscription
    @subscription = current_user.subscription
  end

  # Strong Params;
  # Never Trust Anything From The Pesky Interwebs for Users Are Cunning And [REDACTED]

  def subscription_params
    params.permit(:stripeToken, :plan_id, :trial_end, {user:[:first_name, :last_name, :phone, :email, :address_1, :address_2, :city, :zip, :state, :country]}, {card:[:number, :cvc, :month, :year]})
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/create.html.erb
<h1>Subscriptions#create</h1>
<p>Find me in app/views/subscriptions/create.html.erb</p>

app/views/subscriptions/index.html.erb
<h1>Subscriptions#index</h1>
<p>Find me in app/views/subscriptions/index.html.erb</p>

app/views/subscriptions/new.html.erb
<div class="home_main_container">

	<div class="home_section_container checkout_header">
		<div class="home_middle_container">
			<div class='checkout_header_logo pull-left'>
				<a class="navbar-brand" href="/">REV⚕VE</a>
			</div>
			<div class="checkout_header_phone pull-right">
				<p>Need Support? support@sourcerevive.net</p>
			</div>
		</div>
	</div>

  <%= render 'layouts/flash_errors' %>

  <div class="home_section_container checkout_main_container">
    <div class="home_middle_container">
      <div class='row'>

        <div class="col-xs-8">

          <%= form_tag @subscription, id: 'new_subscription', class: 'revive-form' do %>
            <%= hidden_field_tag :plan_id, params['plan_id'] %>
			      <%= hidden_field_tag :trial_end, params['trial_end'] %>
            <div class="form_section">
              <div class='section_title_container'>
                <div class="step_circle">1</div>
                <div class="step_title_text">Contact Information</div>
              </div>

              <div class='row'>
                <div class='col-xs-6'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[first_name]', nil, placeholder: 'First name' %>
                    </div>
                  </div>
                </div>
                <div class='col-xs-6'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[last_name]', nil, placeholder: 'Last name' %>
                    </div>
                  </div>
                </div>
              </div>

              <div class='row'>
                <div class='col-xs-6'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[email]', current_user ? current_user.email : 'user@example.com', disabled: current_user ? true : false, placeholder: 'Email' %>
                    </div>
                  </div>
                </div>
                <div class='col-xs-6'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[phone]', nil, placeholder: 'Phone' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="form_section">
              <div class='section_title_container'>
                <div class="step_circle">2</div>
                <div class="step_title_text">Billing Details</div>
              </div>

              <div class='row'>
                <div class='col-xs-12'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[address_1]', nil, placeholder: 'Address 1' %>
                    </div>
                  </div>
                </div>
              </div>

              <div class='row'>
                <div class='col-xs-12'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[address_2]', nil, placeholder: 'Address 2' %>
                    </div>
                  </div>
                </div>
              </div>

              <div class='row'>
                <div class='col-xs-4'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[city]', nil, placeholder: 'City' %>
                    </div>
                  </div>
                </div>
                <div class='col-xs-4'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[state]', nil, placeholder: 'State' %>
                    </div>
                  </div>
                </div>
                <div class='col-xs-4'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[zip]', nil, placeholder: 'Zip code' %>
                    </div>
                  </div>
                </div>
              </div>

              <div class='row'>
                <div class='col-xs-12'>
                  <div class="form_field_section">
                    <div class="form_field">
                      <%= text_field_tag 'user[country]', nil, placeholder: 'Country' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="form_section">
              <div class='section_title_container'>
                <div class="step_circle">3</div>
                <div class="step_title_text">Payment Information</div>
              </div>
              <div class="row">
                <div class="col-xs-12">
                  <div id="stripe_error">
                    <noscript>
                      JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
                    </noscript>
                  </div>
                </div>
              </div>
              <section class="card">
                <div class='row'>
                  <div class='col-xs-12'>
                    <div class="payment-errors"></div>
                    <div class="form_field_section">
                      <div class="form_field">
                        <%= text_field_tag 'card[number]', nil, data: {stripe: 'number'}, maxlength: 16, minlength: 16, placeholder: 'Credit card number' %>
                      </div>
                    </div>
                  </div>
                </div>

                <div class='row'>
                  <div class='col-xs-4'>
                    <div class="form_field_section">
                      <div class="form_field">
                        <%= text_field_tag 'card[cvc]', nil, data: {stripe: 'cvc'}, maxlength: 3, minlength: 3, placeholder: 'CVC / CVV' %>
                      </div>
                    </div>
                  </div>
                  <div class='col-xs-4'>
                    <div class="form_field_section">
                      <div class="form_field">
                        <%= text_field_tag 'card[month]', nil, data: {stripe: 'exp-month'}, maxlength: 2, minlength: 2, placeholder: 'Exp. Month' %>
                      </div>
                    </div>
                  </div>
                  <div class='col-xs-4'>
                    <div class="form_field_section">
                      <div class="form_field">
                        <%= text_field_tag 'card[year]', nil, data: {stripe: 'exp-year'}, maxlength: 4, minlength: 2, placeholder: 'Exp. Year' %>
                      </div>
                    </div>
                  </div>
                </div>
              </section>

              <div class="line_break"></div>

              <div class="row trust_logos">
                <!-- <div class="col-xs-6">
                  <div class="row">
                    <div class="col-xs-2">
                      <div class="trust_logo_headline_img">
                        <%= image_tag "http://www.leadpages.net/wp-content/themes/leadpages2014/images/new/homepage/30-badge.png" %>
                      </div>
                    </div>
                    <div class="col-xs-10">
                      <div class="trust_logo_headline pull-left">
                        <p>30 DAY MONEY-BACK GUARANTEE</p>
                      </div>
                    </div>
                  </div>
                </div> -->

                <div class="col-xs-6">
                  <div class="row">
                    <div class="col-xs-1">
                      <div class="trust_logo_headline_img">
                        <%#= image_tag "http://www.leadpages.net/wp-content/themes/leadpages2014/images/new/homepage/30-badge.png" %>
                        <!-- <span class="glyphicon glyphicon-ok pull-left" aria-hidden="true"></span> -->
                        <%= check_box_tag 'accept_terms', 'yes', false, class: 'pull-left' %>
                      </div>
                    </div>
                    <div class="col-xs-10">
                      <div class="trust_logo_headline pull-left">
                        <p>
                          <%#= check_box_tag 'accept_terms' %>
                          <%= link_to 'I agree to the terms', terms_path, target: 'blank', class: 'agree-terms' %>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-xs-6">
                  <div class="row">
                    <div class="col-xs-5">
                      <div class="trust_logo_headline_img pull-right">
                        <i class='glyphicon glyphicon-lock'></i>
                      </div>
                    </div>
                    <div class="col-xs-7">
                      <div class="trust_logo_headline pull-left">
                        <p>SECURE CHECKOUT</p>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

              <div class="panel panel-default order_total_container">
                <div class="panel-heading">
                  <div class="row">
                    <div class="pull-left order_toatal_text">Your Order Total:</div>

						<% if params['trial_end'].to_i != 0 %>
							<div class="pull-right order_toatal_price"><%= params['trial_end'].to_i %> day FREE trial, then $<%= @price %></div>
						<% else %>
							<div class="pull-right order_toatal_price">$<%= @price %></div>
						<% end %>

                  </div>
                </div>
              </div>

              <div class="checkout_form_submit_btn">
                <%= submit_tag "Submit Order", id:'subscription-submit', class:'btn btn-success btn-lg btn-block checkout_form_submit_btn', data:{disable_with:'Working Magic..' }%>
              </div>



            </div>


          <% end %>

        </div>

        <div class="col-xs-4">

          <div class='right_checkout_section'>
            <div class="page-header">
              <h1>What's Included</h1>
            </div>

            <ul class="nav nav-list whats_included_list">
              <li class="pull-left">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                There is no limit to the amount of domains you can find with Source Revive
              </li>

              <li class="pull-left">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                You are allowed an overkill of up to 10  active domain scan projects at a time
              </li>

              <li class="pull-left">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                We handle all the expensive data processing and proxies from our cloud servers.
              </li>

              <li class="pull-left">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                We continue to upgrade and improve this system and keep it pristine.
              </li>
            </ul>

            <hr class="colorgraph">
          </div>

          <!-- <div class='right_checkout_section'>
            <h1>100% Guarantee</h1>


            <div class="satisfaction_checkout_section">
              <%= image_tag 'https://www.leadpages.net/wp-content/themes/leadpages2014/images/new/homepage/30-day-badge.png' %>
            </div>

            <hr class="colorgraph">

          </div> -->

          <div class='right_checkout_section'>
            <h1>Privacy / Security</h1>
            <h4><small>We will not share or trade online information that you provide us (including e-mail addresses). All personal information you submit is encrypted and secure.</small></h4>

            <div class="row text-center">

              <div class="col-xs-6">
                <div class="satisfaction_checkout_section privacy_securty_section pull-left">
                  <%= image_tag 'https://www.safesitecertified.org/members/identity.html?seal=3&member=fa1a21df&location=Traffic_&_Conversion_Summit&size=3&seal_text=115&url=www.trafficandconversionsummit.com/order/recordings/' %>
                </div>
              </div>

              <div class="col-xs-6">
                <div class="satisfaction_checkout_section privacy_securty_section">
                  <%= image_tag 'https://www.safesitecertified.org/members/identity.html?seal=2&member=fa1a21df&location=Traffic_&_Conversion_Summit&size=3&seal_text=115&url=www.trafficandconversionsummit.com/order/recordings/' %>
                </div>
              </div>

            </div>

            <hr class="colorgraph">

          </div>

        </div>

      </div>
    </div>
  </div>

</div>


<script type="text/javascript">
  Stripe.setPublishableKey("<%= ENV['stripe_public_key']%>");
</script>

app/views/subscriptions/reactivate.html.erb
<div class="main_page_container">
	
	<div class='reactivate_header_container'>
		<div class="row">
			<div class='col-xs-12 text-center'>
				<h1>Confirm Your Free 3 Day Trial</h1>
			</div>
		</div>
	
		<div class="row">
	  	  <div class='col-xs-3'></div>
	  	  <div class='col-xs-6 text-center'>
	  		  You will be able to use Revive for 3 days free and then you will be charged on the beggining of the 4th day</div>
	  	  <div class='col-xs-3'></div>
		</div>
	</div>

	

	<div class='reactivate_plan_container'>
		<div class="home_section_container">
			<div class="home_middle_container">
				<!-- <div class="row">
					<div class="text-center">
						<div class="home_video_headline text-center">
							<h1 class="pink_text">Charter Discount Pricing Closes In</h1>
						</div>
						<iframe width="334" height="115" src="https://w2.countingdownto.com/892597" frameborder="0"></iframe>
					</div>
				</div> -->
				<div class="row">
				
					<div class="col-xs-4">
						<div class="pricing_plan_container text-center">
							<div class="plan_title"><h1 class="white-text black_bold_text">EMT</h1></div>
							<div class="pricing_text_container">
								<div><h1 class="white-text black_bold_text">TRIAL</h1></div>
								<div><h4>$199 / per month</h4></div>
							</div>
							<div class="pricing_feature"><h4 class="light_blue_text">Unlimited Domains</h4></div>
							<div class="pricing_feature"><h4 class="light_blue_text">1 Active Project</h4></div>
							<div class="pricing_feature"><h4 class="light_blue_text">For Small/Medium PBNs</h4></div>
							<div class="pricing_feature"><h4 class="light_blue_text">2000 Crawl Minutes</h4></div>
							<div class="pricing_btn">
								
								<%= link_to 'REACTIVATE', create_trial_for_existing_customer_path('plan_id' => 1, 'trial_end' => 3), data: {confirm: 'Yes I want to Sign Up for the 3 day Free Trial to Source Revive!'} %>
							</div>
						</div>
					</div>
				
					<div class="col-xs-4">
						<div class="pricing_plan_container text-center">
							<div class="plan_title pink_title"><h1 class="white-text black_bold_text">DOCTOR</h1></div>
							<div class="pricing_text_container">
								<div><h1 class="white-text black_bold_text">TRIAL</h1></div>
								<div><h4>$297 per month</h4></div>
							</div>
							<div class="pricing_feature"><h4 class="light_blue_text">Unlimited Domains</h4></div>
							<div class="pricing_feature"><h4 class="light_blue_text">1 Active Project</h4></div>
							<div class="pricing_feature"><h4 class="light_blue_text">For Large PBNs</h4></div>
							<div class="pricing_feature yellow_sub"><h4 class="light_blue_text">4000 Crawl Minutes</h4></div>
							<div class="pricing_btn">
								<%= link_to 'REACTIVATE', create_trial_for_existing_customer_path('plan_id' => 3, 'trial_end' => 3), data: {confirm: 'Yes I want to Sign Up for the 3 day Free Trial to Source Revive!'} %>
							</div>
						</div>
					</div>
				
					<div class="col-xs-4">
						<div class="pricing_plan_container text-center">
							<div class="plan_title yellow_title"><h1 class="white-text black_bold_text">IMMORTAL</h1></div>
							<div class="pricing_text_container">
								<!-- <div class="yellow_sub"><h4>Best Value</h4></div> -->
								<div><h1 class="white-text black_bold_text">TRIAL</h1></div>
								<div><h4>$497 per month</h4></div>
							</div>
							<div class="pricing_feature"><h4 class="light_blue_text">Unlimited Domains</h4></div>
							<div class="pricing_feature"><h4 class="light_blue_text">2 Active Projects</h4></div>
							<div class="pricing_feature"><h4 class="light_blue_text">For Agency Level PBNs</h4></div>
							<div class="pricing_feature"><h4 class="light_blue_text">8000 Crawl Minutes</h4></div>
							<div class="pricing_btn">
								<%= link_to 'REACTIVATE', create_trial_for_existing_customer_path('plan_id' => 4, 'trial_end' => 3), data: {confirm: 'Yes I want to Sign Up for the 3 day Free Trial to Source Revive!'} %>
							</div>
						</div>
					</div>
				
				</div>
			</div>
		</div>
	</div>
	
</div>