config/routes.rb
require 'sidekiq/pro/web'

Rails.application.routes.draw do

  root 'plans#index'
  get 'sales', to: 'sales#index', as: 'sales'
  get 'home', to: 'home#index', as: 'home'
  get :dashboard, to: 'dashboard#index'
  
  get 'terms', to: 'home#terms', as: 'terms'
  get 'earnings_disclaimer', to: 'home#earnings_disclaimer', as: 'earnings_disclaimer'
  get 'general_disclaimer', to: 'home#general_disclaimer', as: 'general_disclaimer'

  get 'domains/:id' => "sites#index", as: :domains
  
  get 'copy_to_clipboard' => 'application#copy_to_clipboard', as: :copy_to_clipboard
  
  resource :subscriptions
  get 'create_trial_for_existing_customer' => 'subscriptions#create_trial_for_existing_customer', as: :create_trial_for_existing_customer
  get 'reactivate' => 'subscriptions#reactivate', as: :reactivate
  
  resources :pages
  resources :plans

  resources :users
  resources :sessions
  resources :password_resets
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get :account, to: 'users#account'

  resources :sites do
    collection do
      put 'sites/:id/save_bookmarked' => "sites#save_bookmarked", as: :save_bookmarked
      put 'sites/:id/unbookmark' => "sites#unbookmark", as: :unbookmark
      get ':id/bookmarked' => "sites#bookmarked", as: :bookmarked
    end
  end
  get 'sites/:id/urls' => "sites#all_urls", as: :all_urls
  get 'sites/:id/internal' => "sites#internal", as: :internal
  get 'sites/:id/external' => "sites#external", as: :external
  get 'sites/:id/broken' => "sites#broken", as: :broken
  get 'sites/:id/available' => "sites#available", as: :available

  resources :crawls
  get 'projects/' => "crawls#index", as: :projects
  get 'running_crawls' => "crawls#running", as: :running_crawls
  get 'finished_crawls' => "crawls#finished", as: :finished_crawls
  get 'projects/new' => "crawls#new", as: :new_project
  get 'projects/:id' => "crawls#show", as: :crawl_path
  get 'stop_crawl/:id' => 'crawls#stop_crawl', as: :stop_crawl
  post 'shut_down_crawl' => 'crawls#shut_down_crawl', as: :shut_down_crawl
  get 'crawls/keyword/new' => 'crawls#new_keyword_crawl', as: :new_keyword_crawl
  post 'crawls/keyword/create' => 'crawls#create_keyword_crawl', as: :create_keyword_crawl
  get 'crawls/reverse/new' => 'crawls#new_reverse_crawl', as: :new_reverse_crawl
  post 'crawls/reverse/create' => 'crawls#create_reverse_crawl', as: :create_reverse_crawl
  post 'api_create', to: 'crawls#api_create'
  post 'fetch_new_crawl', to: 'crawls#fetch_new_crawl'
  post 'call_crawl', to: 'crawls#call_crawl'
  post 'migrate_db', to: 'crawls#migrate_db'
  post 'process_new_crawl', to: 'crawls#process_new_crawl'
  get 'start_crawl', to: 'crawls#start_crawl', as: :start_crawl
  get 'delete_crawl/:id', to: 'crawls#delete_crawl', as: :delete_crawl

  resources :pending_crawls do
    collection {post :sort}
  end

  mount Sidekiq::Web, at: '/sidekiq'

end

app/views/nav/_home_top_nav.html.erb
<nav class="navbar navbar-default home_top_nav_container" role="navigation">
	<div class="">
		<div class="row">
			
			<div class="pull-left logo">
				<!-- <div class='revive_top_nav_logo text-center'>
					<a class="navbar-brand" href="/">REV⚕VE</a>
				</div> -->
				<a class="navbar-brand logo_blue_link" href="/">REV⚕VE</a>
			</div>
			
			<div class="pull-right">
				<!-- <div class="navbar-text"><a href="#" class="top_nav_link">ACCOUNT</a></div> -->
				<% if current_user %>
					<div class="navbar-text white_text">Logged in as <%= current_user.email %>.</div>
					<div class="navbar-text"><%= link_to "Log Out", logout_path, class: 'top_nav_link' %></div>
				<% else %>
					<div class="logged_out_nav_text navbar-text">
						<%= link_to 'Home', root_path, class: 'top_nav_link' %>
					</div>
					<div class="logged_out_nav_text navbar-text">
						<%= link_to 'Register', plans_path, class: 'top_nav_link' %>
					</div>
					<div class="logged_out_nav_text navbar-text">
						<%= link_to 'Member Login', login_path, class: 'top_nav_link' %>
					</div>
					<div class="logged_out_nav_text navbar-text">
						<%= link_to 'Support', 'http://source-wave.com/support', class: 'top_nav_link' %>
					</div>
				<% end %>

			</div>

		</div>
	</div>
</nav>

app/views/nav/_left_nav.html.erb
<ul class="left_nav_container">
	
	<li class=<%= 'active' if current_page?(dashboard_path) %> >
		<%= link_to dashboard_path do %>
		    <i class="glyphicon glyphicon-home">
				<span class="glyph_text">Home</span>
			</i>
		<% end %>
	</li>

	<li class=<%= 'active' if current_page?(new_project_path) %> >
		<%= link_to new_project_path do %>
		    <i class="glyphicon glyphicon-plus">
				<span class="glyph_text">New</span>
			</i>
		<% end %>
	</li>

	<li class=<%= 'active' if current_page?(crawls_path) %> >
		<%= link_to crawls_path do %>
		    <i class="glyphicon glyphicon-folder-open">
				<span class="glyph_text">Projects</span>
			</i>
		<% end %>
	</li>

</ul>

app/views/nav/_left_nav_new_ui.html.erb
<ul class="left_nav_container">
  <li <% if @nav == 'dashboard' %>class='active'<% end %>>
    <%= link_to dashboard_path do %>
		  <i class="glyphicon glyphicon-home">
        <span class='glyph_text'>Dashboard</span>
      </i>
    <% end %>
  </li>

  <li <% if @nav == 'new-crawl' %>class='active'<% end %>>
		<%= link_to new_project_path do %>
		    <i class="glyphicon glyphicon-plus">
				<span class="glyph_text">New</span>
			</i>
		<% end %>
	</li>

  <li <% if @nav == 'projects' %>class='active'<% end %>>
    <%= link_to crawls_path do %>
		  <i class="glyphicon glyphicon-folder-close">
        <span class='glyph_text'>Projects</span>
      </i>
    <% end %>
  </li>

  <li <% if @nav == 'domains' %>class='active'<% end %>>
		<%= link_to sites_path('user_id' => current_user.id) do %>
		    <i class="glyphicon glyphicon-th-list">
				<span class="glyph_text">Domains</span>
			</i>
		<% end %>
	</li>

  <li <% if @nav == 'account' %>class='active'<% end %>>
		<%= link_to account_path do %>
		    <i class="glyphicon glyphicon-user">
				<span class="glyph_text">Account</span>
			</i>
		<% end %>
	</li>

  <% if current_user.admin %>
    <li <% if @nav == 'admin' %>class='active'<% end %>>
      <%= link_to admins_path do %>
          <i class="glyphicon glyphicon-cog">
          <span class="glyph_text">Admin</span>
        </i>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/nav/_sales_top_nav.html.erb
<nav class="navbar navbar-default sales-navbar">
  <div class="container-fluid sales-top-nav-padding">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" style="padding-top: 5px;">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="logo_blue_link" href="/">
        <img src="/assets/logo_blue.png" style="width:80px" />
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right sales-navbar-nav">
        <li><a href="#">Home</a></li>
        <li><a href="#">Live Demo</a></li>
        <li><a href="#">Register</a></li>
        <li><a href="#">Member Login</a></li>
        <li><a href="#">Support</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/nav/_top_nav.html.erb
<nav class="navbar navbar-revive">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rev&#9877;ve".html_safe, root_path, class:'navbar-brand' %>
    </div>
    <% if current_user %>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Accounts', account_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", logout_path %></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    <% end %>
  </div><!-- /.container-fluid -->
</nav>